# Generated by Django 3.1.4 on 2023-01-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saladejuntas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='detalle_descripcion',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción'),
        ),
    ]
