# Generated by Django 3.1.4 on 2023-01-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saladejuntas', '0002_sala_detalle_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='color_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Etiqueta Color'),
        ),
    ]
