# Generated by Django 4.1.6 on 2023-02-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saladejuntas', '0004_alter_categoria_id_alter_estatusreuniones_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Registro Activo'),
        ),
    ]
