# Generated by Django 4.1.6 on 2023-04-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saladejuntas', '0005_sala_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='ordenamiento',
            field=models.IntegerField(default=1, null=True, verbose_name='Ordenar'),
        ),
    ]
