# Generated by Django 3.1.4 on 2021-01-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oficios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50, unique=True, verbose_name='Folio')),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='A quien va dirigido')),
                ('puesto', models.CharField(blank=True, max_length=100, verbose_name='Puesto')),
                ('asunto', models.CharField(blank=True, max_length=200, verbose_name='Asunto')),
                ('fecha', models.DateField(blank=True, verbose_name='Fecha')),
                ('usuario', models.CharField(blank=True, max_length=100, verbose_name='Usuario')),
                ('pdf', models.FileField(blank=True, upload_to='media')),
            ],
            options={
                'verbose_name': 'Oficios_Invitacion',
                'verbose_name_plural': 'Oficios_Invitacion',
                'ordering': ['folio'],
            },
        ),
    ]
