# Generated by Django 3.1.4 on 2021-01-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oficios',
            options={'ordering': ['-id'], 'verbose_name': 'Oficios Invitacion', 'verbose_name_plural': 'Oficios Invitacion'},
        ),
        migrations.AddField(
            model_name='oficios',
            name='enviado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Enviado por'),
        ),
        migrations.AddField(
            model_name='oficios',
            name='firma',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='oficios',
            name='asunto',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Asunto'),
        ),
        migrations.AlterField(
            model_name='oficios',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Captura'),
        ),
        migrations.AlterField(
            model_name='oficios',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='A quien va dirigido'),
        ),
        migrations.AlterField(
            model_name='oficios',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='oficios',
            name='puesto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Puesto'),
        ),
        migrations.AlterField(
            model_name='oficios',
            name='usuario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario'),
        ),
    ]
