# Generated by Django 3.1.4 on 2021-01-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0002_auto_20210125_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficios',
            name='estatus',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estatus'),
        ),
    ]
