# Generated by Django 3.1.4 on 2021-02-04 17:24

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oficios', '0003_oficios_estatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recibidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('folio', models.CharField(max_length=50, unique=True, verbose_name='Folio')),
                ('remitente', models.CharField(blank=True, max_length=254, null=True, verbose_name='Remitente')),
                ('puesto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Puesto')),
                ('asunto', models.CharField(blank=True, max_length=254, null=True, verbose_name='Asunto')),
                ('dependencia', models.CharField(blank=True, max_length=254, null=True, verbose_name='Dependencia')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha Recibido')),
                ('fecha_respuesta', models.DateField(blank=True, null=True, verbose_name='Fecha Respuesta')),
                ('usuario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Create_by')),
                ('para', models.CharField(blank=True, max_length=100, null=True, verbose_name='Send_to')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='media/correspondencia')),
                ('comentarios', models.CharField(blank=True, max_length=254, null=True, verbose_name='Comentarios')),
                ('firma', models.CharField(blank=True, max_length=100, null=True, verbose_name='Firma')),
                ('estatus', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estatus')),
                ('area', models.CharField(blank=True, max_length=254, null=True, verbose_name='Area')),
            ],
            options={
                'verbose_name': 'Oficios Recibidos',
                'verbose_name_plural': 'Oficios Recibidos',
            },
        ),
        migrations.AddField(
            model_name='oficios',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='oficios',
            name='dependencia',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Dependencia'),
        ),
        migrations.AddField(
            model_name='oficios',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='oficios',
            name='asunto',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Asunto'),
        ),
        migrations.AlterField(
            model_name='oficios',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='media/correspondencia'),
        ),
        migrations.AlterField(
            model_name='oficios',
            name='usuario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Create_by'),
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=100, verbose_name='Acceso')),
                ('permisos', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permisos Asigandos',
                'verbose_name_plural': 'Permisos Asignados',
                'ordering': ['usuario'],
            },
        ),
        migrations.CreateModel(
            name='Compartidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=100, verbose_name='Acceso')),
                ('compartidos', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permisos Compartidos',
                'verbose_name_plural': 'Permisos Compartidos',
                'ordering': ['usuario'],
            },
        ),
    ]
