# Generated by Django 3.1.4 on 2021-02-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0004_auto_20210204_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibidos',
            name='folio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Folio'),
        ),
    ]
