# Generated by Django 3.1.4 on 2021-02-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0005_auto_20210209_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficios',
            name='nombre',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='A quien va dirigido'),
        ),
        migrations.AlterField(
            model_name='oficios',
            name='puesto',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Puesto'),
        ),
        migrations.AlterField(
            model_name='recibidos',
            name='comentarios',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='recibidos',
            name='puesto',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Puesto'),
        ),
    ]
