# Generated by Django 3.1.4 on 2021-03-02 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0006_auto_20210215_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oficios',
            options={'verbose_name': 'Oficios Invitacion', 'verbose_name_plural': 'Oficios Invitacion'},
        ),
    ]
