# Generated by Django 3.1.4 on 2022-01-19 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oficios', '0008_auto_20220119_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visto', models.BooleanField(default=False)),
                ('oficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficios.recibidos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CCO',
                'verbose_name_plural': 'CCO',
                'ordering': ['id'],
                'unique_together': {('oficio', 'user')},
            },
        ),
        migrations.AddField(
            model_name='recibidos',
            name='copiar_a',
            field=models.ManyToManyField(blank=True, related_name='copiar_a', through='oficios.CCO', to=settings.AUTH_USER_MODEL),
        ),
    ]
