# Generated by Django 3.1.4 on 2022-01-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0009_auto_20220119_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='cco',
            name='comentarios',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Comentarios'),
        ),
    ]
