# Generated by Django 3.1.4 on 2022-01-26 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oficios', '0010_cco_comentarios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cco',
            options={'ordering': ['id'], 'verbose_name': 'Recibidos CC', 'verbose_name_plural': 'Recibidos CC'},
        ),
        migrations.CreateModel(
            name='CC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visto', models.BooleanField(default=False)),
                ('comentarios', models.CharField(blank=True, max_length=400, null=True, verbose_name='Comentarios')),
                ('oficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficios.oficios')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oficios CC',
                'verbose_name_plural': 'Oficion CC',
                'ordering': ['id'],
                'unique_together': {('oficio', 'user')},
            },
        ),
    ]
