# Generated by Django 3.1.4 on 2022-01-26 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oficios', '0011_auto_20220126_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cc',
            options={'ordering': ['id'], 'verbose_name': 'Oficios CC', 'verbose_name_plural': 'Oficios CC'},
        ),
        migrations.AddField(
            model_name='oficios',
            name='copia_a',
            field=models.ManyToManyField(blank=True, related_name='copia_a', through='oficios.CC', to=settings.AUTH_USER_MODEL),
        ),
    ]
