# Generated by Django 3.1.4 on 2022-02-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0013_auto_20220126_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='cco',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='media/correspondencia'),
        ),
        migrations.AddField(
            model_name='cco',
            name='estatus',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estatus'),
        ),
    ]
