# Generated by Django 3.1.4 on 2022-02-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0014_auto_20220201_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='cco',
            name='enviado_por',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Create_by'),
        ),
    ]
