# Generated by Django 3.1.4 on 2022-02-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0016_auto_20220202_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='cco',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo'),
        ),
    ]
