# Generated by Django 3.1.4 on 2022-02-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0018_auto_20220203_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='cco',
            name='fecha_respuesta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Respuesta'),
        ),
        migrations.AddField(
            model_name='cco',
            name='fecha_visto',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Visto'),
        ),
    ]
