# Generated by Django 3.1.4 on 2022-02-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0020_recibidos_cc_externas'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibidos',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Vencimiento'),
        ),
    ]
