# Generated by Django 3.1.4 on 2022-02-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0021_recibidos_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cco',
            name='respuesta',
            field=models.BooleanField(default=False),
        ),
    ]
