# Generated by Django 3.1.4 on 2022-02-14 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20220208_1050'),
        ('oficios', '0022_cco_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibidos',
            name='unidad',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='users.areas'),
            preserve_default=False,
        ),
    ]
