# Generated by Django 3.1.4 on 2022-05-25 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0023_recibidos_unidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos_Recibidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, upload_to='media/correspondencia/%Y/%m/%d/', verbose_name='archivo')),
                ('oficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficios.recibidos')),
            ],
        ),
        migrations.CreateModel(
            name='Archivos_Oficios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, upload_to='media/correspondencia/%Y/%m/%d/', verbose_name='archivo')),
                ('oficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficios.oficios')),
            ],
        ),
    ]
