# Generated by Django 4.1.6 on 2023-05-04 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programacion', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Busquedas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busqueda', models.CharField(blank=True, max_length=200, verbose_name='Busqueda')),
                ('usuario', models.CharField(blank=True, max_length=100, verbose_name='Usuario')),
                ('fecha', models.DateField(blank=True, verbose_name='Fecha')),
                ('is_success', models.BooleanField(blank=True, default=False, verbose_name='Exito')),
            ],
            options={
                'verbose_name': 'Busquedas',
                'verbose_name_plural': 'Busquedas',
                'ordering': ['busqueda'],
            },
        ),
        migrations.CreateModel(
            name='Cartas_Invitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=50, verbose_name='Folio')),
                ('rfc', models.CharField(blank=True, max_length=30, verbose_name='RFC')),
                ('programa', models.CharField(blank=True, max_length=50, null=True, verbose_name='Programa')),
                ('resultado', models.CharField(blank=True, max_length=300, null=True, verbose_name='Nombre')),
                ('fecha_envio', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('estatus', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estatus')),
                ('usuario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario')),
                ('remesa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remesa')),
            ],
        ),
        migrations.CreateModel(
            name='Fiscalizados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('rfc', models.CharField(max_length=20, unique=True, verbose_name='RFC')),
                ('fecha_alta', models.DateField(blank=True, verbose_name='Fecha')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estatus')),
                ('usuario', models.CharField(blank=True, max_length=100, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'RFC No Fiscalizados',
                'verbose_name_plural': 'Fiscalizados',
                'ordering': ['rfc'],
            },
        ),
        migrations.CreateModel(
            name='REC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=20, unique=True, verbose_name='RFC')),
                ('correo', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono')),
                ('nombre', models.CharField(blank=True, max_length=254, null=True, verbose_name='Nombre')),
                ('direccion', models.CharField(blank=True, max_length=254, null=True, verbose_name='Direccion')),
                ('fecha_alta', models.DateField(blank=True, null=True, verbose_name='Fecha Alta')),
            ],
            options={
                'verbose_name': 'REC',
                'verbose_name_plural': 'REC',
                'ordering': ['rfc'],
            },
        ),
        migrations.CreateModel(
            name='REC_Notificados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('rfc', models.CharField(max_length=20, unique=True, verbose_name='RFC')),
                ('nombre', models.CharField(blank=True, max_length=254, null=True, verbose_name='Nombre')),
                ('direccion', models.CharField(blank=True, max_length=254, null=True, verbose_name='Direccion')),
            ],
            options={
                'verbose_name': 'REC Notificados',
                'verbose_name_plural': 'REC Notificados',
                'ordering': ['rfc'],
            },
        ),
        migrations.CreateModel(
            name='Registro_Civil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busqueda', models.CharField(blank=True, max_length=500, verbose_name='Busqueda')),
                ('usuario', models.CharField(blank=True, max_length=100, verbose_name='Usuario')),
                ('fecha', models.DateField(blank=True, verbose_name='Fecha')),
                ('is_success', models.BooleanField(blank=True, default=False, verbose_name='Exito')),
            ],
            options={
                'verbose_name': 'Registro_Civil',
                'verbose_name_plural': 'Registro_Civil',
                'ordering': ['busqueda'],
            },
        ),
        migrations.CreateModel(
            name='Obligaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligacion', models.CharField(blank=True, max_length=254, null=True, verbose_name='Obligacion')),
                ('fecha_alta', models.DateField(blank=True, null=True, verbose_name='Fecha Alta')),
                ('estatus', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estatus')),
                ('objeto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Objeto')),
                ('fecha_bloqueo', models.DateField(blank=True, null=True, verbose_name='Fecha Bloqueo')),
                ('oc', models.CharField(blank=True, max_length=50, null=True, verbose_name='OC')),
                ('rfc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec.rec')),
            ],
            options={
                'verbose_name': 'Obligaciones',
                'verbose_name_plural': 'Obligaciones',
                'ordering': ['rfc'],
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono')),
                ('ext', models.CharField(blank=True, max_length=10, null=True, verbose_name='Extension')),
                ('fecha_alta', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('nombre', models.CharField(blank=True, max_length=254, null=True, verbose_name='Contacto')),
                ('puesto', models.CharField(blank=True, max_length=254, null=True, verbose_name='Puesto')),
                ('direccion', models.CharField(blank=True, max_length=254, null=True, verbose_name='Direccion')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media/contacto', verbose_name='Imagen')),
                ('coordenada', models.CharField(blank=True, max_length=60, null=True, verbose_name='Coordenada')),
                ('visible', models.BooleanField(blank=True, default=False, null=True)),
                ('actualizado', models.BooleanField(blank=True, default=False, null=True)),
                ('usuario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('programa_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programacion.programa')),
                ('rfc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec.rec')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contacto',
                'ordering': ['rfc'],
            },
        ),
        migrations.CreateModel(
            name='BP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parter', models.CharField(blank=True, max_length=50, null=True, verbose_name='Parter')),
                ('rfc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec.rec')),
            ],
            options={
                'verbose_name': 'BP',
                'verbose_name_plural': 'BP',
                'ordering': ['rfc'],
            },
        ),
    ]
