# Generated by Django 3.1.4 on 2021-02-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='puesto',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Puesto'),
        ),
        migrations.AlterField(
            model_name='rec',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefono'),
        ),
    ]
