# Generated by Django 3.1.4 on 2021-02-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0002_auto_20210204_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'ordering': ['rfc'], 'verbose_name': 'Contacto', 'verbose_name_plural': 'Contacto'},
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefono'),
        ),
    ]
