# Generated by Django 3.1.4 on 2021-02-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0004_auto_20210210_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='usuario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario'),
        ),
    ]
