# Generated by Django 3.1.4 on 2021-02-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0005_contacto_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='actualizado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
