# Generated by Django 3.1.4 on 2021-03-05 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0006_contacto_actualizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obligaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligacion', models.CharField(blank=True, max_length=254, null=True, verbose_name='Obligacion')),
                ('fecha_alta', models.DateField(blank=True, null=True, verbose_name='Fecha Alta')),
                ('estatus', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estatus')),
                ('objeto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Objeto')),
                ('fecha_bloqueo', models.DateField(blank=True, null=True, verbose_name='Fecha Bloqueo')),
                ('oc', models.CharField(blank=True, max_length=50, null=True, verbose_name='OC')),
                ('rfc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec.rec')),
            ],
            options={
                'verbose_name': 'Obligaciones',
                'verbose_name_plural': 'Obligaciones',
                'ordering': ['rfc'],
            },
        ),
        migrations.CreateModel(
            name='BP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parter', models.CharField(blank=True, max_length=50, null=True, verbose_name='Parter')),
                ('rfc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec.rec')),
            ],
            options={
                'verbose_name': 'BP',
                'verbose_name_plural': 'BP',
                'ordering': ['rfc'],
            },
        ),
    ]
