# Generated by Django 3.1.4 on 2021-05-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0007_bp_obligaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
