# Generated by Django 3.1.4 on 2021-05-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0008_contacto_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='ext',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Extension'),
        ),
    ]
