# Generated by Django 3.1.4 on 2021-06-09 15:41

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0011_cartas_invitacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiscalizados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('rfc', models.CharField(max_length=20, unique=True, verbose_name='RFC')),
                ('fecha_alta', models.DateField(blank=True, verbose_name='Fecha')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estatus')),
                ('usuario', models.CharField(blank=True, max_length=100, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'RFC No Fiscalizados',
                'verbose_name_plural': 'Fiscalizados',
                'ordering': ['rfc'],
            },
        ),
    ]
