# Generated by Django 3.1.4 on 2021-08-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0012_fiscalizados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro_Civil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busqueda', models.CharField(blank=True, max_length=500, verbose_name='Busqueda')),
                ('usuario', models.CharField(blank=True, max_length=100, verbose_name='Usuario')),
                ('fecha', models.DateField(blank=True, verbose_name='Fecha')),
                ('is_success', models.BooleanField(blank=True, default=False, verbose_name='Exito')),
            ],
            options={
                'verbose_name': 'Registro_Civil',
                'verbose_name_plural': 'Registro_Civil',
                'ordering': ['busqueda'],
            },
        ),
    ]
