# Generated by Django 3.1.4 on 2021-10-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0013_registro_civil'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartas_invitacion',
            name='remesa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Remesa'),
        ),
    ]
