# Generated by Django 3.1.4 on 2022-06-08 20:10

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0014_cartas_invitacion_remesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='REC_Notificados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('rfc', models.CharField(max_length=20, unique=True, verbose_name='RFC')),
                ('nombre', models.CharField(blank=True, max_length=254, null=True, verbose_name='Nombre')),
                ('direccion', models.CharField(blank=True, max_length=254, null=True, verbose_name='Direccion')),
            ],
            options={
                'verbose_name': 'REC Notificados',
                'verbose_name_plural': 'REC Notificados',
                'ordering': ['rfc'],
            },
        ),
    ]
