# Generated by Django 4.1.6 on 2023-05-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0017_alter_bp_id_alter_busquedas_id_and_more'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='bp',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        # migrations.AlterField(
        #     model_name='busquedas',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        # migrations.AlterField(
        #     model_name='cartas_invitacion',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        migrations.AlterField(
            model_name='circulo_credito',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número Cuenta'),
        ),
        # migrations.AlterField(
        #     model_name='fiscalizados',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        # migrations.AlterField(
        #     model_name='obligaciones',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        # migrations.AlterField(
        #     model_name='rec_notificados',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        # migrations.AlterField(
        #     model_name='registro_civil',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        migrations.AlterField(
            model_name='temporal_circulo_credito',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número Cuenta'),
        ),
    ]
