# Generated by Django 4.1.6 on 2023-05-24 22:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codigos_Maestros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, verbose_name='Codigo')),
                ('valor', models.CharField(blank=True, max_length=200, verbose_name='Valor')),
                ('comentario', models.CharField(blank=True, max_length=200, verbose_name='Comentario')),
            ],
            options={
                'verbose_name': 'Codigos Maestros',
                'verbose_name_plural': 'Codigos Maestros',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Dias_Festivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha')),
                ('comentarios', models.CharField(blank=True, max_length=400, null=True, verbose_name='Comentarios')),
                ('is_general', models.BooleanField(default=False, verbose_name='is_general')),
                ('is_estatal', models.BooleanField(default=False, verbose_name='is_estatal')),
                ('is_federal', models.BooleanField(default=False, verbose_name='is_federal')),
            ],
            options={
                'verbose_name': 'Dias Festivos',
                'verbose_name_plural': 'Dias Festivos',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('clave', models.CharField(max_length=2, verbose_name='Clave')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre')),
                ('abrev', models.CharField(max_length=10, verbose_name='Abreviatura')),
                ('activo', models.BooleanField(default=True, verbose_name='Estatus')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Oficinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100, unique=True, verbose_name='Clave')),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('municipio', models.CharField(blank=True, max_length=100, verbose_name='Municipio')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('direccion', models.CharField(blank=True, max_length=300, verbose_name='Direccion')),
            ],
            options={
                'verbose_name': 'Oficinas',
                'verbose_name_plural': 'Oficinas',
                'ordering': ['clave'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('clave', models.CharField(max_length=3, verbose_name='Clave')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='Estatus')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_pertenece', to='home.estado')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['id'],
            },
        ),
    ]
