# Generated by Django 3.1.4 on 2021-11-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficinas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100, unique=True, verbose_name='Clave')),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('municipio', models.CharField(blank=True, max_length=100, verbose_name='Municipio')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('direccion', models.CharField(blank=True, max_length=300, verbose_name='Direccion')),
            ],
            options={
                'verbose_name': 'Oficinas',
                'verbose_name_plural': 'Oficinas',
                'ordering': ['clave'],
            },
        ),
    ]
