# Generated by Django 3.1.4 on 2022-04-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_dias_festivos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dias_festivos',
            options={'ordering': ['fecha'], 'verbose_name': 'Dias Festivos', 'verbose_name_plural': 'Dias Festivos'},
        ),
        migrations.AddField(
            model_name='dias_festivos',
            name='comentarios',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Comentarios'),
        ),
    ]
