# Generated by Django 3.1.4 on 2022-05-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220407_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='dias_festivos',
            name='is_estatal',
            field=models.BooleanField(default=False, verbose_name='is_estatal'),
        ),
        migrations.AddField(
            model_name='dias_festivos',
            name='is_federal',
            field=models.BooleanField(default=False, verbose_name='is_federal'),
        ),
        migrations.AddField(
            model_name='dias_festivos',
            name='is_general',
            field=models.BooleanField(default=False, verbose_name='is_general'),
        ),
    ]
