# Generated by Django 3.1.4 on 2021-02-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='presuntiva',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Presuntiva'),
        ),
    ]
