# Generated by Django 3.1.4 on 2021-03-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0003_auto_20210212_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle',
            name='etapa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Etapa'),
        ),
        migrations.AddField(
            model_name='programa',
            name='etapa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Etapa'),
        ),
    ]
