# Generated by Django 3.1.4 on 2021-04-25 21:48

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0005_cerrados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('alias', models.CharField(max_length=200, verbose_name='Alias')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripcion')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio')),
                ('estatus', models.BooleanField(blank=True, verbose_name='Estatus')),
                ('usuario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='modelos', verbose_name='Archivo')),
            ],
            options={
                'verbose_name': 'Modelos',
                'verbose_name_plural': 'Modelos',
                'ordering': ['alias'],
            },
        ),
        migrations.AlterField(
            model_name='pagos',
            name='ejercicio',
            field=models.IntegerField(blank=True, choices=[(2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021')], null=True, verbose_name='Ejercicio'),
        ),
    ]
