# Generated by Django 3.1.4 on 2021-05-14 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0006_auto_20210425_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelos',
            name='descripcion',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Descripcion'),
        ),
    ]
