# Generated by Django 3.1.4 on 2021-05-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0007_auto_20210513_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivos',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='pagos',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
