# Generated by Django 3.1.4 on 2021-06-11 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0008_auto_20210517_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='programa_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_programa', to='programacion.programa'),
        ),
    ]
