# Generated by Django 3.1.4 on 2021-06-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0010_auto_20210613_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='comentarios',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Comentarios'),
        ),
    ]
