# Generated by Django 3.1.4 on 2021-07-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0011_auto_20210613_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='comentarios',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Comentarios'),
        ),
    ]
