# Generated by Django 3.1.4 on 2021-08-18 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0012_auto_20210721_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivos',
            name='programa_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_programa', to='programacion.programa'),
        ),
    ]
