# Generated by Django 3.1.4 on 2021-09-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0013_auto_20210818_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='interlocutor',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Interlocutor'),
        ),
    ]
