# Generated by Django 3.1.4 on 2022-03-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0016_auto_20220128_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='ejercicio',
            field=models.IntegerField(blank=True, choices=[(2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022')], null=True, verbose_name='Ejercicio'),
        ),
    ]
