# Generated by Django 3.1.4 on 2022-04-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0017_auto_20220309_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='is_close',
            field=models.BooleanField(default=False, verbose_name='Cerrado'),
        ),
    ]
