# Generated by Django 3.1.4 on 2022-07-08 18:22

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0018_programa_is_close'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribuyentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('rfc', models.CharField(blank=True, max_length=30, verbose_name='RFC')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion')),
                ('estatus', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estatus')),
                ('usuario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario')),
                ('comentarios', models.CharField(blank=True, max_length=600, null=True, verbose_name='Comentarios')),
            ],
            options={
                'verbose_name': 'Contribuyentes',
                'verbose_name_plural': 'Contribuyentes',
                'ordering': ['rfc'],
            },
        ),
    ]
