# Generated by Django 3.1.4 on 2022-07-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0019_contribuyentes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribuyentes',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='contribuyentes',
            name='nombre',
        ),
        migrations.AddField(
            model_name='contribuyentes',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Fin'),
        ),
        migrations.AddField(
            model_name='contribuyentes',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio'),
        ),
        migrations.AddField(
            model_name='contribuyentes',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Monto'),
        ),
        migrations.AddField(
            model_name='contribuyentes',
            name='programa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Programa'),
        ),
    ]
