# Generated by Django 3.1.4 on 2022-07-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0021_contribuyentes_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribuyentes',
            name='is_ready',
            field=models.BooleanField(default=False, verbose_name='Completo'),
        ),
    ]
