# Generated by Django 3.1.4 on 2022-07-14 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0023_contribuyentes_modelo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribuyentes',
            old_name='modelo',
            new_name='modelo_id',
        ),
    ]
