# Generated by Django 3.1.4 on 2022-07-14 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0024_auto_20220714_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribuyentes',
            name='modelo_id',
        ),
    ]
