# Generated by Django 3.1.4 on 2022-07-14 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0026_auto_20220714_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribuyentes',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contribuyentes_modelo', to='programacion.modelos'),
        ),
    ]
