# Generated by Django 3.1.4 on 2022-07-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0027_auto_20220714_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribuyentes',
            name='motivo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Motivo'),
        ),
    ]
