# Generated by Django 3.1.4 on 2022-07-18 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0028_contribuyentes_motivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos_Contribuyente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('comentarios', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comentarios')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='media/programacion', verbose_name='Archivo')),
                ('usuario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('contribuyente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_contribuyentes', to='programacion.contribuyentes')),
            ],
            options={
                'verbose_name': 'Archivos Contribuyente',
                'verbose_name_plural': 'Archivos Contribuyente',
                'ordering': ['contribuyente'],
            },
        ),
    ]
