# Generated by Django 3.1.4 on 2022-07-18 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220530_1207'),
        ('programacion', '0029_archivos_contribuyente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impuestos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(blank=True, max_length=20, verbose_name='mes')),
                ('ejericio', models.BooleanField(default=False, verbose_name='año actual')),
                ('ejericio_1', models.BooleanField(default=False, verbose_name='año -1')),
                ('ejericio_2', models.BooleanField(default=False, verbose_name='año -2')),
                ('ejericio_3', models.BooleanField(default=False, verbose_name='año -3')),
                ('ejericio_4', models.BooleanField(default=False, verbose_name='año -4')),
                ('ejericio_5', models.BooleanField(default=False, verbose_name='año -5')),
                ('contribuyente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impuesto_contribuyente', to='programacion.contribuyentes')),
                ('impuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impuesto_impuesto', to='home.codigos_maestros')),
            ],
            options={
                'verbose_name': 'Impuestos',
                'verbose_name_plural': 'Impuestos',
                'ordering': ['contribuyente'],
            },
        ),
    ]
