# Generated by Django 3.1.4 on 2022-07-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0031_auto_20220718_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impuestos',
            name='mes',
        ),
        migrations.AddField(
            model_name='impuestos',
            name='periodo',
            field=models.CharField(blank=True, max_length=20, verbose_name='periodo'),
        ),
    ]
