# Generated by Django 3.1.4 on 2022-07-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0032_auto_20220719_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impuestos',
            old_name='ejericio',
            new_name='ejercicio',
        ),
        migrations.RenameField(
            model_name='impuestos',
            old_name='ejericio_1',
            new_name='ejercicio_1',
        ),
        migrations.RenameField(
            model_name='impuestos',
            old_name='ejericio_2',
            new_name='ejercicio_2',
        ),
        migrations.RenameField(
            model_name='impuestos',
            old_name='ejericio_3',
            new_name='ejercicio_3',
        ),
        migrations.RenameField(
            model_name='impuestos',
            old_name='ejericio_4',
            new_name='ejercicio_4',
        ),
        migrations.RenameField(
            model_name='impuestos',
            old_name='ejericio_5',
            new_name='ejercicio_5',
        ),
    ]
