# Generated by Django 4.1.6 on 2023-02-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quinielas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='partidos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pronostico',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
