# Generated by Django 3.1.4 on 2021-02-18 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Folio')),
                ('rfc', models.CharField(blank=True, max_length=30, verbose_name='RFC')),
                ('programa', models.CharField(blank=True, max_length=50, null=True, verbose_name='Programa')),
                ('presuntiva', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Estimado')),
                ('recaudado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Recaudado')),
                ('dias', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Dias Trasncurridos')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('estatus', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estatus')),
                ('seguimiento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Seguimiento')),
                ('usuario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Padrones',
                'verbose_name_plural': 'Padrones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo')),
                ('comentarios', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comentarios')),
                ('recargos', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Recargos')),
                ('accesorios', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Accesorios')),
                ('impuesto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Impuesto')),
                ('ejercicio', models.IntegerField(blank=True, choices=[(2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021')], null=True, verbose_name='Ejercicio')),
                ('periodo', models.IntegerField(blank=True, choices=[(1, 'ENE'), (2, 'FEB'), (3, 'MAR'), (4, 'ABR'), (5, 'MAY'), (6, 'JUN'), (7, 'JUL'), (8, 'AGO'), (9, 'SEP'), (10, 'OCT'), (11, 'NOV'), (12, 'DIC')], null=True, verbose_name='Periodo')),
                ('usuario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario')),
                ('presuntiva', models.BooleanField(blank=True, default=False, null=True, verbose_name='Presuntiva')),
                ('programa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padrones.programa')),
            ],
            options={
                'verbose_name': 'Pagos',
                'verbose_name_plural': 'Pagos',
                'ordering': ['programa_id'],
            },
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('comentarios', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comentarios')),
                ('estatus', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estatus')),
                ('usuario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario')),
                ('programa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padrones.programa')),
            ],
            options={
                'verbose_name': 'Detalle',
                'verbose_name_plural': 'Detalle',
                'ordering': ['programa_id'],
            },
        ),
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('comentarios', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comentarios')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='media/programacion', verbose_name='Archivo')),
                ('usuario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario')),
                ('programa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padrones.programa')),
            ],
            options={
                'verbose_name': 'Archivos',
                'verbose_name_plural': 'Archivos',
                'ordering': ['programa_id'],
            },
        ),
    ]
