# Generated by Django 3.1.4 on 2021-03-08 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padrones', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Archivos',
            new_name='Archivos_Padrones',
        ),
        migrations.RenameModel(
            old_name='Detalle',
            new_name='Detalle_Padrones',
        ),
        migrations.RenameModel(
            old_name='Pagos',
            new_name='Pagos_Padrones',
        ),
        migrations.RenameModel(
            old_name='Programa',
            new_name='Programa_Padrones',
        ),
    ]
