# Generated by Django 3.1.4 on 2021-05-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padrones', '0003_auto_20210517_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_padrones',
            name='etapa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Etapa'),
        ),
        migrations.AddField(
            model_name='programa_padrones',
            name='etapa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Etapa'),
        ),
    ]
