# Generated by Django 3.1.4 on 2022-01-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padrones', '0005_programa_padrones_no_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa_padrones',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
