# Generated by Django 3.1.4 on 2022-01-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padrones', '0006_programa_padrones_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programas_Recaudacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa', models.CharField(blank=True, max_length=200, null=True, verbose_name='Programa')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Programas',
                'verbose_name_plural': 'Programas',
            },
        ),
    ]
