# Generated by Django 3.1.4 on 2022-10-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padrones', '0008_auto_20220128_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa_padrones',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
