# Generated by Django 4.1.6 on 2023-04-12 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('padrones', '0010_alter_archivos_padrones_id_alter_detalle_padrones_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa_Padrones_Temporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_control', models.CharField(blank=True, max_length=50, null=True, verbose_name='No Control')),
                ('folio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Folio')),
                ('rfc', models.CharField(blank=True, max_length=30, null=True, verbose_name='RFC')),
                ('programa', models.CharField(blank=True, max_length=50, null=True, verbose_name='Programa')),
                ('presuntiva', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Estimado')),
                ('recaudado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Recaudado')),
                ('dias', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Dias Trasncurridos')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion')),
                ('fecha', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha')),
                ('etapa', models.CharField(blank=True, max_length=50, null=True, verbose_name='Etapa')),
                ('estatus', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estatus')),
                ('seguimiento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Seguimiento')),
                ('usuario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario')),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Registro activo')),
            ],
            options={
                'verbose_name': 'Programa Padrones temporal',
                'verbose_name_plural': 'Programas Padrones temporal',
            },
        ),
        migrations.AddField(
            model_name='programa_padrones',
            name='registro_masivo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Registro cargado masivamente'),
        ),
        migrations.CreateModel(
            name='Envio_Insumos_Programas_Padrones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre_archivo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre archivo')),
                ('ruta_archivo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ruta archivo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envio_masivo_insumos_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Envio de insumos programa padrones',
                'verbose_name_plural': 'Envios de insumos programa padrones',
            },
        ),
        migrations.AddField(
            model_name='programa_padrones',
            name='envio_insumos_programa_padrones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programa_padrones_envio_insumos', to='padrones.envio_insumos_programas_padrones'),
        ),
    ]
