"""
Django settings for Recaudacion project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

#from pathlib import Path
import os
from unipath import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
#BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = Path(__file__).ancestor(3)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*&z8mh8ee3fwe6zq(n$g)z09hd9q1*(2o4l-$y)ye=xg2hmlzz'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'rest_framework',
    'ckeditor', # CKEditor config
    'ckeditor_uploader', # CKEditor media uploader
    
    
    'django.contrib.sites', # <-
    # 'allauth',    # <-
    # 'allauth.account',    # <-
    # 'allauth.socialaccount',    # <-
    # 'allauth.socialaccount.providers.google',    # <-

    # local apps
    'applications.users',
    'applications.home',
    'applications.oficios',
    'applications.programacion',
    'applications.rec',
    'applications.padrones',
    'applications.transferidos',
    'applications.promocion',
    'applications.direccion',
    'applications.juridico',
    'applications.quinielas',
    'applications.saladejuntas',
    'applications.tramites',
    'applications.verificacion_vehicular',
]

#AUTHENTICATION_BACKENDS = (
#    'django.contrib.auth.backends.RemoteUserBackend',
#    'django.contrib.auth.backends.ModelBackend',
#)
#SESSION_COOKIE_DOMAIN = '172.31.113.187:81'
#AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.AllowAllUsersModelBackend']
# AUTHENTICATION_BACKENDS = ( 
#     'django.contrib.auth.backends.ModelBackend', 
#     'allauth.account.auth_backends.AuthenticationBackend', 
# )

# SITE_ID = 2
# LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/login/'

# SOCIALACCOUNT_PROVIDERS = {
#     'google': {
#         'SCOPE': [
#             'profile',
#             'email',
#         ],
#         'AUTH_PARAMS': {
#             'access_type': 'online',
#         }
#     }
# }
#SESSION_COOKIE_SECURE = False


# SESSION_COOKIE_DOMAIN = 'localhost'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'Recaudacion.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR.child('templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'applications.users.context_processors.get_access',
            ],
            'libraries':{
                'tags':  'applications.oficios.tags',
                'tagsJuridico':  'applications.juridico.tags',
                'permissions':  'applications.users.permissions',
 
            }
        },
    },
]

WSGI_APPLICATION = 'Recaudacion.wsgi.application'



# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


AUTH_USER_MODEL = 'users.User'

SECURE_CROSS_ORIGIN_OPENER_POLICY = None


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

