# Generated by Django 3.1.4 on 2021-06-15 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('actividad', models.CharField(max_length=200, verbose_name='Actividad')),
                ('descripcion', models.CharField(blank=True, max_length=400, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Actividades',
                'verbose_name_plural': 'Actividades',
                'ordering': ['actividad'],
            },
        ),
        migrations.CreateModel(
            name='Desarrollo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fecha_inicio', models.DateField(blank=True, verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(blank=True, verbose_name='Fecha Fin')),
            ],
            options={
                'verbose_name': 'Desarrollo',
                'verbose_name_plural': 'Desarrollo',
                'ordering': ['id_evento', 'fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Programa_Actualizaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=400, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Programa Actualizaciones',
                'verbose_name_plural': 'Programa Actualizaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('usuario', models.CharField(max_length=100, verbose_name='Usuario')),
                ('rfc', models.CharField(max_length=20, verbose_name='RFC')),
                ('nombre', models.CharField(max_length=254, verbose_name='Nombre')),
                ('fecha', models.DateField(blank=True, verbose_name='Fecha')),
                ('id_desarrollo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visita_desarrollo', to='promocion.desarrollo')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visita',
                'ordering': ['id_desarrollo', 'rfc'],
            },
        ),
        migrations.CreateModel(
            name='Visita_Detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('dato', models.CharField(blank=True, max_length=254, verbose_name='Datos')),
                ('valor', models.CharField(blank=True, max_length=500, verbose_name='Valor')),
                ('id_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_actividad', to='promocion.actividades')),
                ('id_vista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_visita', to='promocion.visita')),
            ],
            options={
                'verbose_name': 'Detalle visita',
                'verbose_name_plural': 'Detalle visita',
                'ordering': ['id_vista'],
            },
        ),
        migrations.CreateModel(
            name='Participantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fecha_inicio', models.DateField(blank=True, verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(blank=True, verbose_name='Fecha Fin')),
                ('id_desarrollo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desarrollo_usuarios', to='promocion.desarrollo')),
                ('id_usuario', models.ManyToManyField(related_name='usuarios_participantes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participantes',
                'verbose_name_plural': 'Participantes',
                'ordering': ['id_desarrollo', 'fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=254, verbose_name='Etiqueta')),
                ('campo', models.CharField(max_length=254, verbose_name='Campo')),
                ('tipo_control', models.CharField(max_length=254, verbose_name='Tipo Control')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('is_required', models.BooleanField(default=True, verbose_name='Requerido')),
                ('consulta', models.CharField(blank=True, max_length=500, null=True, verbose_name='Consulta')),
                ('id_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulario_actividad', to='promocion.actividades')),
            ],
            options={
                'verbose_name': 'Formularios',
                'verbose_name_plural': 'Formularios',
                'ordering': ['id_actividad'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=400, verbose_name='Descripcion')),
                ('direccion', models.CharField(blank=True, max_length=400, verbose_name='Direccion')),
                ('ciudad', models.CharField(blank=True, max_length=200, verbose_name='Ciudad')),
                ('id_programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_programa', to='promocion.programa_actualizaciones')),
            ],
            options={
                'verbose_name': 'Eventos',
                'verbose_name_plural': 'Eventos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='desarrollo',
            name='id_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desarrollo_evento', to='promocion.evento'),
        ),
        migrations.AddIndex(
            model_name='actividades',
            index=models.Index(fields=['actividad'], name='promocion_a_activid_3e272f_idx'),
        ),
        migrations.AddIndex(
            model_name='visita',
            index=models.Index(fields=['id'], name='promocion_v_id_eb8bd1_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['nombre'], name='promocion_e_nombre_5ce13f_idx'),
        ),
        migrations.AddIndex(
            model_name='desarrollo',
            index=models.Index(fields=['id'], name='promocion_d_id_59744e_idx'),
        ),
    ]
