# Generated by Django 3.1.4 on 2021-06-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades',
            name='tipo_tramite',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tipo Tramite'),
        ),
    ]
