# Generated by Django 3.1.4 on 2021-07-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocion', '0002_actividades_tipo_tramite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, verbose_name='Codigo')),
                ('valor', models.CharField(blank=True, max_length=200, verbose_name='Valor')),
                ('comentario', models.CharField(blank=True, max_length=200, verbose_name='Comentario')),
            ],
            options={
                'verbose_name': 'Opciones',
                'verbose_name_plural': 'Opciones',
                'ordering': ['codigo'],
            },
        ),
        migrations.AlterModelOptions(
            name='visita_detalle',
            options={'ordering': ['id_visita'], 'verbose_name': 'Detalle visita', 'verbose_name_plural': 'Detalle visita'},
        ),
        migrations.RenameField(
            model_name='visita_detalle',
            old_name='id_vista',
            new_name='id_visita',
        ),
        migrations.AddField(
            model_name='desarrollo',
            name='estatus',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estatus'),
        ),
        migrations.AddField(
            model_name='visita',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='visita_detalle',
            name='folio',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Folio'),
            preserve_default=False,
        ),
    ]
