# Generated by Django 3.1.4 on 2021-08-03 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promocion', '0003_auto_20210707_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='desarrollo',
            name='responsables',
            field=models.ManyToManyField(blank=True, related_name='responsables', to=settings.AUTH_USER_MODEL),
        ),
    ]
