# Generated by Django 3.1.4 on 2022-03-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocion', '0005_visita_detalle_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa_actualizaciones',
            name='estatus',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estatus'),
        ),
        migrations.AddField(
            model_name='programa_actualizaciones',
            name='objetivo',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Objetivo'),
        ),
    ]
