# Generated by Django 3.1.4 on 2022-03-17 17:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('promocion', '0006_auto_20220316_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa_actualizaciones',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='programa_actualizaciones',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('estatus', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estatus')),
                ('comentarios', models.CharField(blank=True, max_length=600, null=True, verbose_name='Comentarios')),
                ('usuario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_programa', to='promocion.programa_actualizaciones')),
            ],
            options={
                'verbose_name': 'Detalle',
                'verbose_name_plural': 'Detalle',
                'ordering': ['programa'],
            },
        ),
    ]
