# Generated by Django 3.1.4 on 2022-03-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocion', '0007_auto_20220317_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa_actualizaciones',
            name='usuario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario'),
        ),
    ]
