# Generated by Django 3.1.4 on 2022-03-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocion', '0008_programa_actualizaciones_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='desarrollo',
            name='comentarios',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Comentarios'),
        ),
        migrations.AddField(
            model_name='desarrollo',
            name='fecha_fin_calidad',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Fin Calidad'),
        ),
        migrations.AddField(
            model_name='desarrollo',
            name='fecha_fin_campo',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Fin Campo'),
        ),
        migrations.AddField(
            model_name='desarrollo',
            name='fecha_inicio_calidad',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio Calidad'),
        ),
        migrations.AddField(
            model_name='desarrollo',
            name='fecha_inicio_campo',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio Campo'),
        ),
        migrations.AddField(
            model_name='desarrollo',
            name='jefatura',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Jefatura'),
        ),
        migrations.AddField(
            model_name='evento',
            name='km2_recorridos',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Km2 Recorridos'),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estatus'),
        ),
        migrations.AddField(
            model_name='evento',
            name='unidades_censadas',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Unidades Censadas'),
        ),
    ]
