# Generated by Django 3.1.4 on 2022-05-25 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre')),
                ('valor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Valor')),
                ('auxiliar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Auxiliar')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='Sort')),
                ('agrupador', models.CharField(max_length=100, verbose_name='Agrupador')),
                ('is_active', models.BooleanField(default=True)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijo', to='juridico.catalogo')),
            ],
            options={
                'verbose_name': 'Catalogo',
                'verbose_name_plural': 'Catalogos',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carpeta', models.CharField(max_length=300, verbose_name='Carpeta')),
                ('expediente', models.CharField(max_length=300, verbose_name='Expediente')),
                ('fecha_aviso', models.DateField(blank=True, null=True, verbose_name='Aviso')),
                ('fecha_notificacion', models.DateField(blank=True, null=True, verbose_name='Notificacion')),
                ('fecha_interno', models.DateField(blank=True, null=True, verbose_name='Interno')),
                ('fecha_fatal', models.DateField(blank=True, null=True, verbose_name='Fatal')),
                ('resolucion_impg', models.CharField(max_length=2000, verbose_name='Resolucion_Impg')),
                ('cuantia', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cuantia')),
                ('contribuyente', models.CharField(blank=True, max_length=200, null=True, verbose_name='Contribuyente')),
                ('abogado_prom', models.CharField(blank=True, max_length=200, null=True, verbose_name='Abogado_Prom')),
                ('fecha_resolucion', models.DateField(blank=True, null=True, verbose_name='Resolucion')),
                ('resolucion_rec', models.CharField(blank=True, max_length=200, null=True, verbose_name='Resolucion_Rec')),
                ('fecha_contestacion', models.DateField(blank=True, null=True, verbose_name='Contestacion')),
                ('oficio', models.CharField(blank=True, max_length=300, null=True, verbose_name='Oficio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autoridad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autoridadDemanda', to='juridico.catalogo')),
                ('autoridad_rec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurridaDemanda', to='juridico.catalogo')),
                ('dictaminador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictaminador_Demanda', to=settings.AUTH_USER_MODEL)),
                ('estado_procesal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proceso_Demanda', to='juridico.catalogo')),
                ('juicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_Juicio', to='juridico.catalogo')),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiaDemanda', to='juridico.catalogo')),
                ('subtipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_Demanda', to='juridico.catalogo')),
                ('tribunal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tribunal_Demanda', to='juridico.catalogo')),
            ],
            options={
                'verbose_name': 'Demanda',
                'verbose_name_plural': 'Demandas',
            },
        ),
        migrations.CreateModel(
            name='Dias_Festivos_Estatal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha')),
                ('comentarios', models.CharField(blank=True, max_length=400, null=True, verbose_name='Comentarios')),
            ],
            options={
                'verbose_name': 'Dias Festivos',
                'verbose_name_plural': 'Dias Festivos',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Dias_Festivos_Federal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha')),
                ('comentarios', models.CharField(blank=True, max_length=400, null=True, verbose_name='Comentarios')),
            ],
            options={
                'verbose_name': 'Dias Festivos',
                'verbose_name_plural': 'Dias Festivos',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Texto')),
            ],
            options={
                'verbose_name': 'Mouse',
                'verbose_name_plural': 'Mouses',
                'ordering': ['Nombre'],
            },
        ),
        migrations.CreateModel(
            name='Rubros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('interno', models.IntegerField(blank=True, null=True, verbose_name='Valor')),
                ('fatal', models.IntegerField(blank=True, null=True, verbose_name='Auxiliar')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='Sort')),
                ('agrupador', models.CharField(max_length=100, verbose_name='Agrupador')),
                ('is_active', models.BooleanField(default=True)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijo', to='juridico.rubros')),
            ],
            options={
                'verbose_name': 'Rubro',
                'verbose_name_plural': 'Rubros',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Procesal_Detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato', models.CharField(blank=True, max_length=254, verbose_name='Datos')),
                ('comentario', models.CharField(blank=True, max_length=500, verbose_name='Valor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demanda_Detalle', to='juridico.demanda')),
                ('procesal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesal_Detalle', to='juridico.rubros')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictaminador_procesal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Procesal detalle',
                'verbose_name_plural': 'Procesal detalle',
                'ordering': ['demanda'],
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=254, verbose_name='Etiqueta')),
                ('campo', models.CharField(max_length=254, verbose_name='Campo')),
                ('tipo_control', models.CharField(max_length=254, verbose_name='Tipo Control')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('is_required', models.BooleanField(default=True, verbose_name='Requerido')),
                ('consulta', models.CharField(blank=True, max_length=500, null=True, verbose_name='Consulta')),
                ('detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IdDetalle', to='juridico.catalogo')),
            ],
            options={
                'verbose_name': 'Formulario',
                'verbose_name_plural': 'Formularios',
                'ordering': ['detalle'],
            },
        ),
    ]
