# Generated by Django 3.1.4 on 2022-06-21 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('juridico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos_Juridico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, upload_to='juridico/%Y/%m/%d/', verbose_name='archivo')),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fecha_interno', models.DateField(blank=True, null=True, verbose_name='proceso_interno')),
                ('fecha_fatal', models.DateField(blank=True, null=True, verbose_name='proceso_fatal')),
                ('fecha_cierre', models.DateField(blank=True, null=True, verbose_name='proceso_cierre')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creacion_proceso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proceso',
                'verbose_name_plural': 'Proceso',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Proceso_Detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('folio', models.PositiveIntegerField(blank=True, verbose_name='Folio')),
                ('dato', models.CharField(blank=True, max_length=254, verbose_name='Datos')),
                ('valor', models.CharField(blank=True, max_length=500, verbose_name='Valor')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='juridico/', verbose_name='Archivo')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creacion_detalle', to=settings.AUTH_USER_MODEL)),
                ('id_proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juridico.proceso')),
            ],
            options={
                'verbose_name': 'Proceso Detalle',
                'verbose_name_plural': 'Proceso Detalle',
                'ordering': ['id_proceso'],
            },
        ),
        migrations.DeleteModel(
            name='Dias_Festivos_Estatal',
        ),
        migrations.DeleteModel(
            name='Dias_Festivos_Federal',
        ),
        migrations.DeleteModel(
            name='Mouse',
        ),
        migrations.AlterModelOptions(
            name='formulario',
            options={'ordering': ['id'], 'verbose_name': 'Formulario', 'verbose_name_plural': 'Formularios'},
        ),
        migrations.RemoveField(
            model_name='demanda',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='demanda',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='detalle',
        ),
        migrations.RemoveField(
            model_name='rubros',
            name='padre',
        ),
        migrations.AddField(
            model_name='demanda',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creacion_Demanda', to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demanda',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='estatus'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='rfc',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Rfc'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='plantilla_form',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='plantilla_form'),
        ),
        migrations.AddField(
            model_name='rubros',
            name='etapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubro_catalogo', to='juridico.catalogo'),
        ),
        migrations.AddField(
            model_name='rubros',
            name='etapa_siguiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubro_etapa_siguiente', to='juridico.catalogo'),
        ),
        migrations.AddField(
            model_name='rubros',
            name='formulario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Formulario'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='abogado_prom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='abogadoPromovente', to='juridico.catalogo'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Procesal_Detalle',
        ),
        migrations.AddField(
            model_name='proceso',
            name='demanda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demanda_proceso', to='juridico.demanda'),
        ),
        migrations.AddField(
            model_name='proceso',
            name='etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapa_proceso', to='juridico.catalogo'),
        ),
        migrations.AddField(
            model_name='proceso',
            name='rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubro_proceso', to='juridico.rubros'),
        ),
        migrations.AddField(
            model_name='archivos_juridico',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juridico.proceso'),
        ),
    ]
