# Generated by Django 3.1.4 on 2022-08-22 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0003_auto_20220818_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='abogado_prom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abogadoPromovente', to='juridico.catalogo'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='cuantia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Cuantia'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='resolucion_impg',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Resolucion_Impg'),
        ),
    ]
