# Generated by Django 3.1.4 on 2022-08-23 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0004_auto_20220822_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijo', to='juridico.proceso'),
        ),
    ]
