# Generated by Django 3.1.4 on 2022-08-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0005_proceso_padre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso_detalle',
            name='valor',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Valor'),
        ),
    ]
