# Generated by Django 3.1.4 on 2022-09-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0006_auto_20220824_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='resolucion',
            field=models.BooleanField(blank=True, null=True, verbose_name='resolucion'),
        ),
    ]
