# Generated by Django 3.1.4 on 2022-09-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0007_demanda_resolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='estatus'),
        ),
    ]
