# Generated by Django 4.1.6 on 2023-05-25 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_estado_municipio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('juridico', '0009_alter_archivos_juridico_id_alter_catalogo_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('obligatorio', models.BooleanField(default=False, verbose_name='Obligatorio')),
                ('formato_default', models.BooleanField(default=False, verbose_name='Formato por defecto')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='juridico/resolutor/%Y/', verbose_name='Archivo')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('tramite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tramite', to='juridico.catalogo')),
            ],
            options={
                'verbose_name': 'Requisito',
                'verbose_name_plural': 'Requisitos',
            },
        ),
        migrations.CreateModel(
            name='Resolutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('carpeta', models.CharField(max_length=300, verbose_name='Carpeta')),
                ('oficio', models.CharField(max_length=300, verbose_name='Oficio')),
                ('fecha_presentacion', models.DateField(verbose_name='Fecha_presentacion')),
                ('fecha_resolucion', models.DateField(blank=True, null=True, verbose_name='Fecha_resolucion')),
                ('ejercicio_ini', models.IntegerField(verbose_name='ejercicio_ini')),
                ('ejercicio_fin', models.IntegerField(verbose_name='ejercicio_fin')),
                ('marca', models.CharField(max_length=300, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=300, verbose_name='Modelo')),
                ('serie', models.CharField(max_length=300, verbose_name='Serie')),
                ('placa', models.CharField(max_length=300, verbose_name='Placa')),
                ('fecha_notificacion', models.DateField(blank=True, null=True, verbose_name='Fecha_notificacion')),
                ('monto', models.IntegerField(blank=True, null=True, verbose_name='monto')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('abogado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abogado_resolutor', to=settings.AUTH_USER_MODEL)),
                ('concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Concepto', to='juridico.catalogo')),
                ('documentacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Documentacion', to='juridico.catalogo')),
                ('formato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Formato', to='juridico.catalogo')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Municipio', to='home.municipio')),
                ('sentido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sentido', to='juridico.catalogo')),
            ],
            options={
                'verbose_name': 'Resolutor',
                'verbose_name_plural': 'Resolutores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('rfc', models.CharField(max_length=15, verbose_name='Rfc')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('apeP', models.CharField(max_length=50, verbose_name='ApeP')),
                ('apeM', models.CharField(max_length=50, verbose_name='ApeM')),
                ('calle', models.CharField(max_length=200, verbose_name='calle')),
                ('numero', models.IntegerField(verbose_name='numero')),
                ('colonia', models.CharField(max_length=200, verbose_name='colonia')),
                ('ciudad', models.CharField(max_length=200, verbose_name='ciudad')),
                ('cp', models.IntegerField(verbose_name='cp')),
                ('telefono', models.BigIntegerField(verbose_name='telefono')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'Solicitante',
                'verbose_name_plural': 'Solicitantes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Resolutor_detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarios', models.CharField(max_length=300, verbose_name='comentarios')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='juridico/resolutor/%Y/', verbose_name='Archivo')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('estatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_estatus', to='juridico.catalogo')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_etapa', to='juridico.catalogo')),
                ('requisito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolutor_requisito', to='juridico.requisitos')),
                ('resolutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_resolutor', to='juridico.resolutor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resolutor_detalle',
                'verbose_name_plural': 'Resolutores_detalle',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='resolutor',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitante_resolutor', to='juridico.solicitante'),
        ),
        migrations.AddField(
            model_name='resolutor',
            name='titular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titular', to=settings.AUTH_USER_MODEL),
        ),
    ]
