# Generated by Django 4.1.6 on 2023-05-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0010_requisitos_resolutor_solicitante_resolutor_detalle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolutor',
            name='ejercicio_fin',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ejercicio_fin'),
        ),
        migrations.AlterField(
            model_name='resolutor',
            name='ejercicio_ini',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ejercicio_ini'),
        ),
    ]
