# Generated by Django 4.1.6 on 2023-03-28 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_tus', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Estatus',
            },
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tramite', models.CharField(blank=True, max_length=50, verbose_name='Tipo Tramite')),
            ],
            options={
                'verbose_name': 'Tramite',
                'verbose_name_plural': 'Tramites',
            },
        ),
    ]
