# Generated by Django 4.1.6 on 2023-03-28 03:35

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0002_estatus_tramite'),
    ]

    operations = [
        migrations.CreateModel(
            name='NuevoTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confianza', models.BooleanField(blank=True, default=False, null=True)),
                ('honorarios', models.BooleanField(blank=True, default=False, null=True)),
                ('plaza', models.BooleanField(blank=True, default=False, null=True)),
                ('titulo_formato', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='q', null=True)),
                ('servicio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Servicio')),
                ('comentarios', models.CharField(blank=True, max_length=100, null=True, verbose_name='Comentarios')),
                ('estatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estatus', to='tramites.estatus')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos', to='tramites.tipos')),
                ('tramite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tramite', to='tramites.tramite')),
            ],
            options={
                'verbose_name': 'Tramite nuevo',
                'verbose_name_plural': 'Tramites nuevos',
            },
        ),
    ]
