# Generated by Django 4.1.6 on 2023-03-28 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tramites', '0003_nuevotramite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estatus_Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=500, verbose_name='Descripción')),
                ('is_active', models.BooleanField(verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Estatus solicitud',
                'verbose_name_plural': 'Estatus solicitudes',
            },
        ),
        migrations.CreateModel(
            name='Requisitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('obligatorio', models.BooleanField(default=False, verbose_name='Obligatorio')),
                ('tiene_formato_default', models.BooleanField(default=False, verbose_name='¿Tiene formato por defecto?')),
                ('ruta_formato', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL')),
                ('ruta_nombre_archivo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre archivo')),
                ('tramite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tramite_requisitos', to='tramites.nuevotramite')),
            ],
            options={
                'verbose_name': 'Requisito tramite',
                'verbose_name_plural': 'Requesitos tramite',
            },
        ),
        migrations.CreateModel(
            name='Observaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones')),
                ('fecha_realizada', models.DateField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('tramite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nuevo_tramite_observaciones', to='tramites.nuevotramite')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_observaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Observaciones',
                'verbose_name_plural': 'Observaciones',
            },
        ),
    ]
