# Generated by Django 4.1.6 on 2023-03-28 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tramites', '0004_estatus_solicitud_requisitos_observaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('folio', models.CharField(blank=True, max_length=15, null=True, verbose_name='Folio')),
                ('vigencia', models.IntegerField(blank=True, null=True, verbose_name='Vigencia')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_vigencia', models.DateField(blank=True, null=True, verbose_name='Fecha de vigencia')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha final')),
                ('observaciones', models.CharField(blank=True, max_length=600, null=True, verbose_name='Observaciones')),
                ('estatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estatus_solicitud_tramite', to='tramites.estatus_solicitud')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramite_solicitud_tramite', to='tramites.nuevotramite')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_solicitud_tramite', to=settings.AUTH_USER_MODEL)),
                ('usuario_autorizo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_autorizo_solicitud_tramite', to=settings.AUTH_USER_MODEL)),
                ('usuario_reviso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_reviso_solicitud_tramite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de trámites',
                'verbose_name_plural': 'Solicitudes de trámites',
            },
        ),
        migrations.CreateModel(
            name='Detalle_Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('requisito_nombre', models.CharField(blank=True, max_length=600, null=True, verbose_name='Requisito')),
                ('es_obligatorio', models.BooleanField(verbose_name='¿Es obligatorio?')),
                ('nombre_archivo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre archivo')),
                ('ruta_archivo', models.CharField(blank=True, max_length=600, null=True, verbose_name='Ruta archivo')),
                ('estatus', models.CharField(max_length=255, verbose_name='Estatus')),
                ('folio_temporal', models.CharField(blank=True, max_length=15, null=True, verbose_name='Folio Temporal')),
                ('observaciones', models.CharField(blank=True, max_length=600, null=True, verbose_name='Observaciones')),
                ('requisito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisito_detalle_solicitud', to='tramites.requisitos')),
                ('solicitud_tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_solicitudes_tramites', to='tramites.solicitud')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_detalle_solicitud_tramite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle solicitud trámite',
                'verbose_name_plural': 'Detalles solicitud trámite',
            },
        ),
    ]
