# Generated by Django 4.1.6 on 2023-03-28 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tramites', '0005_solicitud_detalle_solicitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial_Solicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('observaciones', models.CharField(blank=True, max_length=600, null=True, verbose_name='Observaciones')),
                ('estatus_detalle_solicitud', models.CharField(blank=True, max_length=255, null=True, verbose_name='Estatus detalle solicitud')),
                ('detalle_solicitud_tramite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalle_solicitud_historial_solicitudes', to='tramites.detalle_solicitud')),
                ('estatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estatus_historial_solicitud', to='tramites.estatus_solicitud')),
                ('solicitud_tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_historial_solicitudes', to='tramites.solicitud')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_historial_solicitudes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial solicitud',
                'verbose_name_plural': 'Historial solicitudes',
            },
        ),
        migrations.CreateModel(
            name='Detalle_solicitud_temporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('folio', models.CharField(max_length=15, verbose_name='Folio')),
                ('requisito_nombre', models.CharField(max_length=600, verbose_name='Requisito')),
                ('es_obligatorio', models.BooleanField(verbose_name='¿Es obligatorio?')),
                ('nombre_archivo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre archivo')),
                ('ruta_archivo', models.CharField(blank=True, max_length=600, null=True, verbose_name='Ruta archivo')),
                ('estatus', models.CharField(max_length=255, verbose_name='Estatus')),
                ('observaciones', models.CharField(blank=True, max_length=600, null=True, verbose_name='Observaciones')),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisito_detalle_solicitud_tmp', to='tramites.requisitos')),
                ('solicitud_tramite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalle_tmp_solicitudes_tramites', to='tramites.solicitud')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_detalle_tmp_solicitud_tramite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Temporal detalle solicitud trámite',
                'verbose_name_plural': 'Temporal detalles solicitud trámite',
            },
        ),
    ]
