# Generated by Django 3.1.4 on 2022-10-31 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombres', models.CharField(blank=True, max_length=50)),
                ('apellidos', models.CharField(blank=True, max_length=50)),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('avatar', models.FileField(blank=True, null=True, upload_to='users', verbose_name='Avatar')),
                ('telefono', models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefono')),
                ('ext', models.CharField(blank=True, max_length=5, null=True, verbose_name='Ext')),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, verbose_name='Urls')),
                ('icono', models.CharField(blank=True, max_length=100, null=True, verbose_name='Icono')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('tags', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tags')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='Sort')),
                ('nivel', models.IntegerField(blank=True, null=True, verbose_name='Nivel')),
                ('is_active', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='users.urls')),
            ],
            options={
                'verbose_name': 'Urls',
                'verbose_name_plural': 'Urls',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orientacion', models.IntegerField(default=0, verbose_name='Orientacion')),
                ('barra', models.IntegerField(default=0, verbose_name='Barra')),
                ('menu', models.IntegerField(default=0, verbose_name='Menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantilla', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla',
                'verbose_name_plural': 'Plantilla',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('clave', models.CharField(blank=True, max_length=100, null=True, verbose_name='Clave')),
                ('is_active', models.BooleanField(default=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='users.areas')),
            ],
            options={
                'verbose_name': 'Areas',
                'verbose_name_plural': 'Areas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Accesos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('urls', models.ManyToManyField(blank=True, related_name='get_urls', to='users.Urls')),
            ],
            options={
                'verbose_name': 'Accesos',
                'verbose_name_plural': 'Accesos',
                'ordering': ['perfil'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='areas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_area', to='users.areas'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='jefe_directo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jerarquia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_unidad', to='users.areas'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
