# Generated by Django 3.1.4 on 2021-05-15 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_user_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, verbose_name='Urls')),
                ('icono', models.CharField(blank=True, max_length=100, null=True, verbose_name='Icono')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('tags', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tags')),
                ('padre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Padre')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='Sort')),
            ],
            options={
                'verbose_name': 'Urls',
                'verbose_name_plural': 'Urls',
                'ordering': ['url'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Accesos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('urls', models.ManyToManyField(blank=True, related_name='get_urls', to='users.Urls')),
            ],
            options={
                'verbose_name': 'Accesos',
                'verbose_name_plural': 'Accesos',
                'ordering': ['perfil'],
            },
        ),
    ]
