# Generated by Django 3.1.4 on 2021-05-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210515_0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urls',
            options={'ordering': ['sort'], 'verbose_name': 'Urls', 'verbose_name_plural': 'Urls'},
        ),
        migrations.AddField(
            model_name='urls',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
