# Generated by Django 3.1.4 on 2021-05-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210516_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
