# Generated by Django 3.1.4 on 2021-09-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_plantilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='nivel',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nivel'),
        ),
    ]
