# Generated by Django 3.1.4 on 2021-09-18 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_urls_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='users.urls'),
        ),
    ]
