# Generated by Django 3.1.4 on 2021-09-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210918_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='user',
            name='ext',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ext'),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telefono'),
        ),
    ]
