# Generated by Django 3.1.4 on 2021-09-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210921_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='users', verbose_name='Avatar'),
        ),
    ]
