# Generated by Django 3.1.4 on 2022-02-08 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210921_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jefe_directo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jerarquia', to=settings.AUTH_USER_MODEL),
        ),
    ]
