# Generated by Django 3.1.4 on 2022-02-08 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='areas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_area', to='users.areas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='unidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_unidad', to='users.areas'),
            preserve_default=False,
        ),
    ]
