# Generated by Django 3.1.4 on 2022-03-01 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20220208_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='areas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_area', to='users.areas'),
        ),
        migrations.AlterField(
            model_name='user',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_unidad', to='users.areas'),
        ),
    ]
