# Generated by Django 3.1.4 on 2023-01-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20220301_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='areas',
            name='correo_notificacion_coffe_break',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Correo Notificación Coffe Break'),
        ),
    ]
