# Generated by Django 3.1.4 on 2022-10-07 15:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programa_Transferidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nuevo_folio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nuevo Folio')),
                ('folio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Folio')),
                ('rfc', models.CharField(blank=True, max_length=30, verbose_name='RFC')),
                ('programa', models.CharField(blank=True, max_length=50, null=True, verbose_name='Programa')),
                ('presuntiva', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Estimado')),
                ('recaudado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Recaudado')),
                ('dias', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Dias Trasncurridos')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('etapa', models.CharField(blank=True, max_length=50, null=True, verbose_name='Etapa')),
                ('estatus', models.CharField(blank=True, max_length=400, null=True, verbose_name='Estatus')),
                ('seguimiento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Seguimiento')),
                ('usuario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario')),
                ('area', models.CharField(blank=True, max_length=200, null=True, verbose_name='Area')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activo')),
                ('comentarios', models.CharField(blank=True, max_length=600, null=True, verbose_name='Comentarios')),
                ('metodo_envio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Metodo Envio')),
                ('ejercicio', models.IntegerField(blank=True, choices=[(2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022')], null=True, verbose_name='Ejercicio')),
                ('periodo', models.IntegerField(blank=True, choices=[(1, 'ENE'), (2, 'FEB'), (3, 'MAR'), (4, 'ABR'), (5, 'MAY'), (6, 'JUN'), (7, 'JUL'), (8, 'AGO'), (9, 'SEP'), (10, 'OCT'), (11, 'NOV'), (12, 'DIC')], null=True, verbose_name='Periodo')),
                ('is_close', models.BooleanField(default=False, verbose_name='Cerrado')),
            ],
            options={
                'verbose_name': 'Programacion',
                'verbose_name_plural': 'Programacion',
                'ordering': ['nuevo_folio'],
            },
        ),
        migrations.CreateModel(
            name='Temporal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(blank=True, max_length=30, verbose_name='RFC')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion')),
                ('presuntiva', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Presuntiva')),
                ('programa', models.CharField(blank=True, max_length=50, null=True, verbose_name='Programa')),
                ('metodo_envio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Metodo Envio')),
                ('ejercicio', models.IntegerField(blank=True, null=True, verbose_name='Ejercicio')),
                ('periodo', models.IntegerField(blank=True, null=True, verbose_name='Periodo')),
                ('estatus', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estatus')),
                ('unidad_responsable', models.CharField(blank=True, max_length=200, null=True, verbose_name='Unidad Responsable')),
            ],
            options={
                'verbose_name': 'Temporal',
                'verbose_name_plural': 'Temporal',
                'ordering': ['rfc'],
            },
        ),
        migrations.CreateModel(
            name='Pagos_Transferidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo')),
                ('comentarios', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comentarios')),
                ('recargos', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Recargos')),
                ('accesorios', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Accesorios')),
                ('impuesto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Impuesto')),
                ('ejercicio', models.IntegerField(blank=True, choices=[(2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021')], null=True, verbose_name='Ejercicio')),
                ('periodo', models.IntegerField(blank=True, choices=[(1, 'ENE'), (2, 'FEB'), (3, 'MAR'), (4, 'ABR'), (5, 'MAY'), (6, 'JUN'), (7, 'JUL'), (8, 'AGO'), (9, 'SEP'), (10, 'OCT'), (11, 'NOV'), (12, 'DIC')], null=True, verbose_name='Periodo')),
                ('usuario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario')),
                ('presuntiva', models.BooleanField(blank=True, default=False, null=True, verbose_name='Presuntiva')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('programa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transferidos.programa_transferidos')),
            ],
            options={
                'verbose_name': 'Pagos',
                'verbose_name_plural': 'Pagos',
                'ordering': ['programa_id'],
            },
        ),
        migrations.CreateModel(
            name='Detalle_Transferidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('comentarios', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comentarios')),
                ('etapa', models.CharField(blank=True, max_length=50, null=True, verbose_name='Etapa')),
                ('estatus', models.CharField(blank=True, max_length=400, null=True, verbose_name='Estatus')),
                ('usuario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('programa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_programa', to='transferidos.programa_transferidos')),
            ],
            options={
                'verbose_name': 'Detalle',
                'verbose_name_plural': 'Detalle',
                'ordering': ['programa_id'],
            },
        ),
        migrations.CreateModel(
            name='Archivos_Transferidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('comentarios', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comentarios')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='media/programacion', verbose_name='Archivo')),
                ('usuario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('programa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transferidos.programa_transferidos')),
            ],
            options={
                'verbose_name': 'Archivos',
                'verbose_name_plural': 'Archivos',
                'ordering': ['programa_id'],
            },
        ),
    ]
