# Generated by Django 3.1.4 on 2021-04-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa_transferidos',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='programa_transferidos',
            name='nuevo_folio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nuevo Folio'),
        ),
    ]
