# Generated by Django 3.1.4 on 2021-04-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferidos', '0002_auto_20210412_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programa_transferidos',
            options={'ordering': ['nuevo_folio'], 'verbose_name': 'Programacion', 'verbose_name_plural': 'Programacion'},
        ),
        migrations.AddField(
            model_name='programa_transferidos',
            name='comentarios',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comentarios'),
        ),
    ]
