# Generated by Django 3.1.4 on 2021-05-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferidos', '0003_auto_20210430_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivos_transferidos',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='detalle_transferidos',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='pagos_transferidos',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='pagos_transferidos',
            name='ejercicio',
            field=models.IntegerField(blank=True, choices=[(2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021')], null=True, verbose_name='Ejercicio'),
        ),
    ]
