# Generated by Django 3.1.4 on 2021-08-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferidos', '0005_auto_20210715_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_transferidos',
            name='estatus',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Estatus'),
        ),
    ]
