# Generated by Django 3.1.4 on 2021-10-18 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transferidos', '0007_auto_20210801_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_transferidos',
            name='programa_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_programa', to='transferidos.programa_transferidos'),
        ),
    ]
