# Generated by Django 3.1.4 on 2022-01-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferidos', '0008_auto_20211018_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa_transferidos',
            name='metodo_envio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Metodo Envio'),
        ),
    ]
