# Generated by Django 3.1.4 on 2022-02-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferidos', '0010_auto_20220128_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa_transferidos',
            name='comentarios',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Comentarios'),
        ),
    ]
