# Generated by Django 3.1.4 on 2022-03-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferidos', '0011_auto_20220214_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa_transferidos',
            name='ejercicio',
            field=models.IntegerField(blank=True, choices=[(2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022')], null=True, verbose_name='Ejercicio'),
        ),
        migrations.AddField(
            model_name='programa_transferidos',
            name='periodo',
            field=models.IntegerField(blank=True, choices=[(1, 'ENE'), (2, 'FEB'), (3, 'MAR'), (4, 'ABR'), (5, 'MAY'), (6, 'JUN'), (7, 'JUL'), (8, 'AGO'), (9, 'SEP'), (10, 'OCT'), (11, 'NOV'), (12, 'DIC')], null=True, verbose_name='Periodo'),
        ),
    ]
