# Generated by Django 3.1.4 on 2022-03-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferidos', '0012_auto_20220309_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temporal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(blank=True, max_length=30, verbose_name='RFC')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion')),
                ('programa', models.CharField(blank=True, max_length=50, null=True, verbose_name='Programa')),
                ('metodo_envio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Metodo Envio')),
                ('ejercicio', models.IntegerField(blank=True, null=True, verbose_name='Ejercicio')),
                ('periodo', models.IntegerField(blank=True, null=True, verbose_name='Periodo')),
                ('estatus', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estatus')),
                ('unidad_responsable', models.CharField(blank=True, max_length=200, null=True, verbose_name='Unidad Responsable')),
            ],
            options={
                'verbose_name': 'Temporal',
                'verbose_name_plural': 'Temporal',
                'ordering': ['rfc'],
            },
        ),
        migrations.AlterField(
            model_name='pagos_transferidos',
            name='ejercicio',
            field=models.IntegerField(blank=True, choices=[(2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021')], null=True, verbose_name='Ejercicio'),
        ),
        migrations.AlterField(
            model_name='programa_transferidos',
            name='ejercicio',
            field=models.IntegerField(blank=True, choices=[(2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022')], null=True, verbose_name='Ejercicio'),
        ),
    ]
