# Generated by Django 3.1.4 on 2022-03-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferidos', '0013_auto_20220328_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporal',
            name='presuntiva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Presuntiva'),
        ),
    ]
