# Generated by Django 3.1.4 on 2022-10-10 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '__first__'),
        ('transferidos', '0014_temporal_presuntiva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impuestos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(blank=True, max_length=20, verbose_name='periodo')),
                ('ejercicio', models.IntegerField(blank=True, verbose_name='año actual')),
                ('ejercicio_1', models.IntegerField(blank=True, verbose_name='año -1')),
                ('ejercicio_2', models.IntegerField(blank=True, verbose_name='año -2')),
                ('ejercicio_3', models.IntegerField(blank=True, verbose_name='año -3')),
                ('ejercicio_4', models.IntegerField(blank=True, verbose_name='año -4')),
                ('ejercicio_5', models.IntegerField(blank=True, verbose_name='año -5')),
                ('contribuyente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impuesto_transferidos', to='transferidos.programa_transferidos')),
                ('impuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impuesto_obligaciones', to='home.codigos_maestros')),
            ],
            options={
                'verbose_name': 'Impuestos',
                'verbose_name_plural': 'Impuestos',
                'ordering': ['contribuyente'],
            },
        ),
    ]
