# Generated by Django 3.1.4 on 2022-10-07 15:14

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transferidos', '0015_impuestos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('llave', models.CharField(blank=True, max_length=200, null=True, verbose_name='Llave')),
                ('valor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Valor')),
                ('etapa', models.CharField(blank=True, max_length=200, null=True, verbose_name='Llave')),
                ('estatus', models.CharField(blank=True, max_length=200, null=True, verbose_name='Llave')),
                ('tipo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Llave')),
                ('is_active', models.BooleanField(default=True, verbose_name='estatus')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
